spring.datasource.url=jdbc:postgresql://dpg-d75bjkruibrs7386e0hg-a.singapore-postgres.render.com:5432/qrmenu_ganb?sslmode=require
spring.datasource.username=qrmenu_ganb_user
spring.datasource.password=3tmq4gFXUiBw0RTdeACRV27cERc8qoyS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8081}
server.address=0.0.0.0