spring.datasource.url=jdbc:postgresql://dpg-d75bjkruibrs7386e0hg-a:5432/qrmenu_ganb
spring.datasource.username=qrmenu_ganb_user
spring.datasource.password=3tmq4gFXUiBwORTdeACRV27cERc8qoyS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG

server.port=${PORT:8080}
